#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$application = new \Symfony\Component\Console\Application();

$application->add(
    new \romanzipp\MotoGP\Commands\GenerateCalendarCommand()
);

$application->run();
