#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$dotenv = new \Symfony\Component\Dotenv\Dotenv();
$dotenv->load(__DIR__ . '/.env');

$application = new \Symfony\Component\Console\Application();

$application->add(
    new \romanzipp\CalendarGenerator\Commands\GenerateCalendarCommand()
);

$application->add(
    new \romanzipp\CalendarGenerator\Commands\ListCalendarsCommand()
);

$application->run();
